csandman/chakra-react-select

package-lock.json, package.json
Chakra now allows for `framer-motion@5` so the `peerDependencies` have been updated to reflect that: https://github.com/chakra-ui/chakra-ui/commit/04774e2196b9f3e8edd77f779e8c15981e8d8135#diff-1f344ac391eeecc21ec0f01fb07430a47f4b80d20485c125447d54c33c4bbfc4
=> Update `framer-motion` peer dependency

package-lock.json, package.json, src/chakra-react-select.tsx
- Add the `className`s react-select uses to all of the custom components implemented in this wrapper
- Enable the functionality of the `classNamePrefix` prop for all components which it previously did now work for
=> Add class names to all components

package-lock.json, package.json
v6 of framer-motion contains no breaking change which affects `chakra-react-select`, see https://github.com/framer/motion/blob/main/CHANGELOG.md#600-2022-01-19
Chakra UI itself has also updated the peer dependency recently: https://github.com/chakra-ui/chakra-ui/pull/5499
=> Remove `peerDeps` which are already enforced via Chakra UI itself

README.md, package-lock.json, package.json, src/use-chakra-select-props.ts
- Allow the `styles` prop to be forwarded to the inner select in order to style the `MenuPortal` component
- Add documentation for styling the `MenuPortal` component
=> `MenuPortal` Fix

README.md, package-lock.json, package.json, src/index.ts
- Export the [`useChakraSelectProps`](https://github.com/csandman/chakra-react-select/blob/main/src/use-chakra-select-props.ts) hook publicly
- Add documentation on how to use the `useChakraSelectProps` hook
=> Public `useChakraSelectProps` hook

package-lock.json, package.json, src/types.ts
- Change the default value for the `IsMulti` generic on the `ChakraStylesConfig` interface to be `boolean` instead of `false`
- This is based on the [`StylesConfig`](https://github.com/JedWatson/react-select/blob/fe7dab371290b87c425d9036b66febcf4d1beead/packages/react-select/src/styles.ts#L96) type from `react-select`
- For some reason, while in most places [the `IsMulti` generic defaults to `false`](https://react-select.com/typescript), in this instance it needs to be set to `boolean`
=> ChakraStylesConfig generic default fix

README.md, package-lock.json, package.json
This starts with #73 which points out that when multiple instances of `@emotion/react` are installed, you receive the following warning:
> You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.
Before [`react-select@5.3.1`](https://github.com/JedWatson/react-select/releases/tag/react-select%405.3.1), the versions of `@emotion/react` required by Chakra UI and React Select were largely compatible (`^11.0.0` vs. `^11.1.1`). In the most recent version of `react-select` however, they bumped their `@emotion/react` dependency to `^11.8.1`, the third most recent version. This means that it is far more likely that users of this package will run into …
=> Add @emotion/react@11.8.1 as a peer dependency

babel.config.js, package-lock.json, package.json, tsconfig.json
- Update to `react-select@5.3.2`
- Update `babel.config.js` to closer match [Chakra UI's](https://github.com/chakra-ui/chakra-ui/blob/790d2417a3f5d59e2d69229a027af671c2dc0cbc/babel.config.js)
- Update `tsconfig.json` to closer match [Chakra UI's](https://github.com/chakra-ui/chakra-ui/blob/790d2417a3f5d59e2d69229a027af671c2dc0cbc/tsconfig.json)
- Clean up `package.json`
- Add a new `format` script
- Add new tags
- Downgrade react dev dependencies to match this version of chakra
- Update remaining dev dependencies:
```shell
@typescript-eslint/eslint-plugin  ^5.22.0  →  ^5.23.0     
@typescript-eslint/parser         ^5.22.0  →  ^5.23.0     
eslint                            ^8.14.0  →  ^8.15.0     
husky                              ^7.0.4  →   ^8.0.1
```
=> Update to react-select 5.3.2

tsconfig.json
- Fix the types being built by removing `incremental` from `tsconfig.json`
- closes #123
=> Fix the types being built by removing "increcemental" from tsconfig

tsconfig.json
- Fix the types being built by removing `incremental` from `tsconfig.json`
- closes #123
=> Fix the types being built

README.md, package.json
- Update documentation and npm tag for making v3 of `chakra-react-select` a legacy version
- This version will be maintained to support `@chakra-ui/react@1` and `react@17`
=> V3 Legacy Version

src/chakra-components/containers.tsx, src/chakra-components/control.tsx, src/chakra-components/group.tsx, src/chakra-components/indicators.tsx, src/chakra-components/menu.tsx, src/chakra-components/multi-value.tsx, src/chakra-components/option.tsx
- Add the `data-focus-visible` prop to all components that had `data-focus` in order to reenable focus styles.  The components affected are the `Control`, `ClearIndicator`, and `MultiValueRemove`.
- Slightly tweak the dropdown indicator styles for the `useBasicStyles` prop.
- Remove all type casting for the `size` prop, instead using a default size of `"md"`.
=> Focus Visible Fix

README.md, package-lock.json, package.json, src/chakra-components/containers.tsx, src/chakra-components/control.tsx, src/module-augmentation.ts
- Fix the bug allowing users to remove selected options when `isDisabled` is passed - closes #168
- Small README edits
- Add an example CodeSandbox for each of the custom props that are available
- Change some general wording and explanations in the docs
=> Fix: Prevent a selected option from being removed when isDisabled is passed

README.md, src/chakra-components/control.tsx, src/chakra-components/input.tsx, src/module-augmentation.ts, src/use-chakra-select-props.ts
- Add functionality to the previously undocumented prop `isReadOnly`
- Add documentation for this new prop
- Remove the cursor styling for the `DropdownIndicator`
=> Make the `isReadOnly` prop functional

src/use-chakra-select-props.ts
- The `menuIsOpen` prop was broken in [`v4.2.1`](https://github.com/csandman/chakra-react-select/releases/tag/v4.2.1) due to a missing parenthesis...
closes #176
=> Fix the `menuIsOpen` prop

package.json
- Fix the `types` export in the `exports` field by making it non-last
- This fixes a bug caused by #188 that broke the `"exports"` field in the `package.json` in certain environments.
- The solution comes from this comment: https://github.com/csandman/chakra-react-select/issues/187#issuecomment-1259601597
- See #187 for more info
=> Fix the types export in the exports field of the package.json by making it non-last

src/chakra-components/menu.tsx
- Change the `minW` of the `MenuList` to allow it to be smaller than it is in Chakra's default theme
=> MenuList width fix

src/chakra-components/menu.tsx
- Fix an overflow issue causing `MenuList` shadow to get cut off - closes #208
- Fix was done by removing `overflow: hidden` on the `Menu` component, which, as far as I'm aware, isn't needed for anything anyway
- In addition, made some other styles for the `Menu` and `MenuList` more closely align with the original styles from `react-select`
=> Menu shadow fix

README.md, src/chakra-components/control.tsx, src/use-chakra-select-props.ts
- Use the `defaultProps` from Chakra's `Input` component theme to determine the default `size` and `variant` that will be applied to the `Select`
- This was requested specifically for the `variant` prop in #207 but it applied well to the `size` prop too
- Update the [Theme Styles](https://github.com/csandman/chakra-react-select#theme-styles) section of the README to explain how some styles are overridden.  See #194
=> Default Props from Input

src/chakra-components/menu.tsx
=> fix: hover styling missing

src/index.ts
This PR is to fix a part of what's going on in #229, at least the main issue described.  However, I don't believe this is a solution to making `chakra-react-select` work with [the Nextjs 13 `app` directory structure](https://beta.nextjs.org/docs/getting-started), but it should at least remove the warning.
The warning is fixed by being more explicit about what to export from `react-select`'s sub-packages instead of exporting all children.
=> Fix `conflicting star exports` bug

.eslintrc, README.md, src/module-augmentation.ts, src/types.ts, src/use-chakra-select-props.ts
- Add the option to use custom variants for the `Input` and `Tag` components, pulled from the theme
- closes #215
=> Custom Variants

src/use-chakra-select-props.ts
Closes #263 
This PR implements the `isRequired` prop from the form control (or the one passed directly to the component), forwarding it to the internal `required` prop on the internal React Select component. This get's forwarded down to a hidden input which also receives the `name` prop for use with built in form validation.
This prop will be overridden if you pass `required` to the select component directly, similar to how this works with the original react select.
Here is the example used in the original issue: https://codesandbox.io/s/prod-browser-17s6f4 (see below for the generated CodeSandbox with this fix implemented).
---
**EDIT:** Here is the rendered HTML of the hidden input from the original CodeSandbox example:
```html
<input required="" name="chakra-select" tabindex="-1" …
```
=> fix: Make the `isRequired` prop forward to the internal `required` prop

package-lock.json, package.json, src/module-augmentation.ts
This PR is a part two to #284 in which I fixed the broken module augmentation for projects using TypeScript with `moduleResolution="bundler"`. I finally got some replies on my PR to the react select project: https://github.com/JedWatson/react-select/pull/5762#issuecomment-1762700437
And the maintainers basically explained that the method for implementing the module augmentation in the docs was outdated. The new approach is to augment them from the higher level (and already public) package `react-select/base`:
> Thanks for the PR but these internal files aren't really intended to be public API and be augmented directly like this so I don't think this makes sense to merge.
> 
> The various types here can already be augmented by using the place where they're exported publicly. e.g. the …
=> fix: Fix module augmentation and install latest version of `react-select` again

src/chakra-components/control.tsx, src/chakra-components/input.tsx, src/chakra-components/menu.tsx, src/index.ts, src/module-augmentation.ts, src/types.ts, src/utils.ts
closes #295 
---
This PR is in response to #295. I had already found the fix for this issue, so this PR just implements it. The solution was just to implement some code I had missed from the original [`GroupHeading`](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Group.tsx#L141-L155) component.
It also implements a few other cleanup changes:
- Simplify the theme types by using Chakra's built in [`ThemeTypings`](https://github.com/chakra-ui/chakra-ui/blob/61f965a4143012658156d362e809fdd9b0a616f5/packages/core/styled-system/src/shared.types.ts) interface.
- Update a few TSDoc comments and their links
- Unify some variable names and types
- Add some aria props and change some of the style configs to use them. This was initially proposed in #283, …
=> chore: Fix `GroupHeading` props + some other cleanup

src/chakra-components/containers.tsx, src/chakra-components/control.tsx
Issue: on `chakra-react-select` v3 users can remove selected options when `isDisabled` is passed using
Reported here for v4:  https://github.com/csandman/chakra-react-select/issues/168
Fixed here for > v4: https://github.com/csandman/chakra-react-select/pull/169
This PR aims to fix this issue for v3
=> Fix for V3: Prevent a selected option from being removed when isDisabled is passed

src/index.ts
After my [previous change](https://github.com/csandman/chakra-react-select/pull/298) to switch to `tsup` for building the project, I had to do a lot of shifting types around to ensure the module augmentation to add the custom props was still working properly. However, I realized that after doing so I ended up exporting the core `Props` type from `react-select/base` instead of just `react-select`. These do not have an identical type definition as the props that are normally exported, and thus can't be used to define props external to a select component in the same way.
To fix this, I stopped exporting the props, and switched my main import for these base props:
```tsx
import type { Props } from "react-select/base";
```
to an export:
```tsx
export type { Props as ReactSelectBaseProps } from …
```
=> fix: Fix `react-select` core `Props` type export

package-lock.json, package.json, tsup.config.ts
Closes #329 
This PR removes the `"type": "module"` config from the `package.json`, in order to fix the path that Jest is pulling the package from. I'm not really an expert on Jest and where it pulls it's imports from, but the issue #329 appears to be caused by a mismatch of ESM and CJS imports. The goal of `v4.9` was really to enable ESM imports in general, and this still works without using the `module` type, because the ESM version is pulled using the `exports` field (if the environment is setup correctly).
So, after changing the `type` back to `commonjs` (by just removing it, `commonjs` is the default), the fix with the consistent IDs (#298) still appears to work fine for me in my test environment, so I'm fine with this approach. Plus, this actually better matches the package exports …
=> fix: Change package `type` back to default of `"commonjs"`

src/use-chakra-select-props.ts
This PR removed the default value provided for the `tagColorScheme` prop in favor of using whatever color scheme the user has provided to their base Chakra theme. It does the same for the base variant provided.
With the following theme code:
```tsx
const tagTheme = extendTheme({
components: {
Tag: defineStyleConfig({
defaultProps: {
colorScheme: "blue",
variant: "solid",
},
}),
},
});
const App: NextPage = () => (
<ChakraProvider theme={tagTheme}>
<FormControl>
<FormLabel>Multi with custom tag theme</FormLabel>
<Select
isMulti
options={groupedOptions}
/>
</FormControl>
</ChakraProvider>
);
```
The output was rendered with the proper theme styles:
=> feat: Use default tag theme props if provided

.codesandbox/ci.json, .eslintrc, package-lock.json, package.json, src/chakra-components/containers.tsx, src/chakra-components/control.tsx, src/chakra-components/input.tsx, src/chakra-components/menu.tsx, src/chakra-components/multi-value.tsx, src/chakra-components/placeholder.tsx, src/chakra-components/single-value.tsx, src/index.ts, src/select/async-creatable-select.tsx, src/select/async-select.tsx, src/select/creatable-select.tsx, src/select/select.tsx, src/types.ts, src/use-chakra-select-props.ts, src/utils.ts, tsconfig.json
This PR fixes #335 by removing the peer dependencies on the sub-packages of `@chakra-ui/react` and switches to depend on the full package. This is something I've been meaning to do for a while, and already made the change for my upcoming `v5` release (#323), as the peer sub-packages have been frustrating to people.
As of `@chakra-ui/react@2.9.1`, this now becomes a required change due to their switching to switching to a single package approach, because the peer dependencies of the individual sub-dependencies are no longer installed at the top level: https://github.com/chakra-ui/chakra-ui/pull/8153
Here are some notes one why I wanted to make this change before this breaking change anyway from #323:
---
> There has been a lot of back and forth on whether this package should use …
=> fix: Switch dependencies to depend on `@chakra-ui/react` instead of sub-packages

package-lock.json, package.json, src/chakra-components/menu.tsx
This PR fixes the issue described in #308. It removes the `_selected` check for the menu option style overrides because it was too specific. Sorry for the delay on this one, I completely forgot about this being an issue. The fix basically just reverts the change that was made in [`v4.7.6`](https://github.com/csandman/chakra-react-select/releases/tag/v4.7.6): [`v4.7.5...v4.7.6`#diff-282462b390](https://github.com/csandman/chakra-react-select/compare/v4.7.5...v4.7.6#diff-282462b390ca3390d40b92e5bb7575995e675a710c8958176ffbae47e15a3411R412-R429)
---
One also small change, is that I generalized the dependency version of `react-select` to be `5.8.x`.
=> fix: Reduce selected menu option styles specificity

README.md, package.json, tsup.config.ts
This PR implements two changes. The first is to expand the `import` and `require` sections of the `exports` field in the `package.json`. I've been noticing some packages have been splitting these out in order to specify a `types` object for each version of the build. tsup already generated a different types file for each build type automatically, so this seems like a good practice to ensure that when the user is importing the types, they're coming from the right place.
Previously I was just relying on the types paths being inferred from the JS file's import path. This seems to have been working fine, but I believe that regardless of whether you were using CJS or ESM, only the `index.d.ts` file would ever be imported.
This is in-line with how the new `@chakra-ui/react` pacakge.json is …
=> Improve the `exports` and modify the tsup build config

src/chakra-components/menu.tsx
This PR closes #352 
There was an issue with the menu scrolling behavior using the arrow keys due to removed relative positioning on the `MenuList` component. You can see where it was removed in V6 here: https://github.com/csandman/chakra-react-select/pull/341/files#diff-282462b390ca3390d40b92e5bb7575995e675a710c8958176ffbae47e15a3411L116
This was most likely removed by mistake in an attempt to clean up as many style overrides as possible.
=> fix: Re-add relative positioning to MenuList

demo/package-lock.json, demo/package.json, package-lock.json, package.json
This PR is meant to be applied in `v5` branch
This PR updates the `react-select` dependency to the latest version which is fully compatible with React 19.
It also solves issue #356
Reference: https://github.com/JedWatson/react-select/releases
=> [v5] Libraries - Update react-select to 5.10.0

demo/package-lock.json, demo/package.json, package-lock.json, package.json
This PR updates the `react-select` dependency to the latest version. I realized after starting it that #357 did the same thing, but I also updated some of the other dev dependencies, so I'll still push this up.
I also removed the extra dependency of `react-select` from the demo package.json, as it didn't need to be there (just doing an `npm install` in the demo folder after updating the parent package's dependency would do the trick).
Finally, it adds the `chakra2` tag to the release config, so that future releases aren't marked as `latest`.
=> chore: Update dev dependencies

README.md, demo/package-lock.json, package-lock.json, package.json
This PR just updates the peer dependency range for React and React DOM to include v19. I realized that the latest version of Chakra v2 actually also supports v19, so this package definitely should too!
I also updated the docs for how to install v5 of this package, as it now requires appending `@chakra2` or `@5` to the package name.
This PR actually closes #356 this time.
=> chore: Update React/React DOM dependency ranges
